imports:
    - { resource: "parameters.yml" }
    - { resource: "services.yml" }
    - { resource: "grids.yml" }

sylius_resource:
    resources:
        webburza_wishlist.wishlist:
            classes:
                repository: '%webburza_wishlist.repository.wishlist.class%'
                factory: '%webburza_wishlist.factory.wishlist.class%'
                model: '%webburza_wishlist.model.wishlist.class%'
                form: '%webburza_wishlist.form.type.admin_wishlist.class%'

        webburza_wishlist.wishlist_item:
            classes:
                model: '%webburza_wishlist.model.wishlist_item.class%'

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    WebburzaSyliusWishlistBundle:
                        type: xml
                        prefix: Webburza\Sylius\WishlistBundle\Model
                        dir: 'Resources/config/doctrine'
                        is_bundle: true
                        mapping: true

        resolve_target_entities:
            Sylius\Component\Core\Model\ShopUserInterface: '%sylius.model.shop_user.class%'
            Webburza\Sylius\WishlistBundle\Model\WishlistInterface: '%webburza_wishlist.model.wishlist.class%'
            Webburza\Sylius\WishlistBundle\Model\WishlistItemInterface: '%webburza_wishlist.model.wishlist_item.class%'

twig:
    globals:
        wishlist_provider: '@webburza_wishlist.provider.wishlist'

webburza_sylius_wishlist:
    multiple: false
    default_public: false
