# ------------------------------------------------------------------------------
#  FRONTEND
# ------------------------------------------------------------------------------

# Show the first wishlist for the current user, only if the bundle
# is configured for a single wishlist per user, otherwise redirect
webburza_frontend_wishlist_first:
    path: /
    methods: [GET]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist:firstAction

webburza_frontend_wishlist_show:
    path: /{slug}/
    methods: [GET]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist:showAction

webburza_frontend_wishlist_clear:
    path: /{id}/clear/
    methods: [POST]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist:clearAction

webburza_frontend_wishlist_add_item:
    path: /item/
    methods: [POST]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist_item:addAction

webburza_frontend_wishlist_remove_item:
    path: /item/{id}/
    methods: [DELETE]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist_item:removeAction

webburza_frontend_wishlist_partial_cart_add_item:
    path: /item/add-to-cart/
    methods: [GET]
    defaults:
        _controller: webburza_wishlist.controller.front.wishlist_item:addToCartAction
