services:
    webburza_wishlist.listener.menu_builder:
        class: '%webburza_wishlist.listener.menu_builder.class%'
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addBackendMenuItems }

    webburza_wishlist.listener.menu_builder_account:
        class: '%webburza_wishlist.listener.menu_builder_account.class%'
        arguments:
            - '@translator'
            - '@security.token_storage'
            - '@webburza_wishlist.repository.wishlist'
            - '%webburza_sylius_wishlist.multiple%'
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }

    webburza_wishlist.listener.user:
        class: '%webburza_wishlist.listener.user.class%'
        arguments: ['@service_container']
        tags:
            - { name: 'doctrine.event_listener', event: 'onFlush' }
            - { name: 'doctrine.event_listener', event: 'postFlush' }

    webburza_wishlist.factory.plain.wishlist:
        class: '%webburza_wishlist.factory.plain.wishlist.class%'
        arguments:
            - '%webburza_wishlist.model.wishlist.class%'

    webburza_wishlist.factory.wishlist:
        class: '%webburza_wishlist.factory.wishlist.class%'
        arguments:
            - '@webburza_wishlist.factory.plain.wishlist'
            - '@translator'
            - '%webburza_sylius_wishlist.default_public%'

    webburza_wishlist.controller.front.wishlist:
        class: '%webburza_wishlist.controller.front.wishlist.class%'
        arguments: ['@service_container']

    webburza_wishlist.controller.account.wishlist:
        class: '%webburza_wishlist.controller.account.wishlist.class%'
        arguments: ['@service_container']

    webburza_wishlist.controller.front.wishlist_item:
        class: '%webburza_wishlist.controller.front.wishlist_item.class%'
        arguments: ['@service_container']

    webburza_wishlist.provider.wishlist:
        class: '%webburza_wishlist.provider.wishlist.class%'
        arguments:
            - '@webburza_wishlist.repository.wishlist'
            - '@security.token_storage'

    webburza_wishlist.form.type.admin_wishlist:
        class: '%webburza_wishlist.form.type.admin_wishlist.class%'
        arguments:
            - '%webburza_wishlist.model.wishlist.class%'
        tags:
            - { name: form.type, alias: webburza_admin_wishlist }

    webburza_wishlist.form.type.wishlist:
        class: '%webburza_wishlist.form.type.wishlist.class%'
        arguments:
            - '%webburza_wishlist.model.wishlist.class%'
        tags:
            - { name: form.type, alias: webburza_wishlist }

    webburza_wishlist.form.type.user_choice:
        class: '%webburza_wishlist.form.type.user_choice.class%'
        arguments:
            - '@sylius.repository.shop_user'
        tags:
            - { name: form.type, alias: webburza_wishlist_user_choice }

    webburza_wishlist.resolver.product_variant_cart:
        class: '%webburza_wishlist.resolver.product_variant_cart.class%'
        arguments:
            - '@sylius.repository.product'
            - '@sylius.factory.add_to_cart_command'
            - '@sylius.context.cart'
            - '@sylius.factory.cart_item'
            - '@form.factory'
